# Generated by Django 6.0.3 on 2026-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_telehealthconsultation_consultationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientscan',
            name='disease_causes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='disease_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='disease_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='herbal_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='telemetry_targets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='untreated_consequences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
